# Generated by Django 2.1.7 on 2019-04-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='menu',
            field=models.BooleanField(default=False, max_length=64, verbose_name='菜单栏'),
        ),
    ]
